import = ["/Users/saish/dotfiles/.config/alacritty/alacritty-master/dracula.toml"]
#[[colors.indexed_colors]]
#color = "#EF9F76"
#index = 16
#
#[[colors.indexed_colors]]
#color = "#F2D5CF"
#index = 17
#
#[colors.bright]
#black = "#626880"
#blue = "#8CAAEE"
#cyan = "#81C8BE"
#green = "#A6D189"
#magenta = "#F4B8E4"
#red = "#E78284"
#white = "#A5ADCE"
#yellow = "#E5C890"
#
#[colors.cursor]
#cursor = "#F2D5CF"
#text = "#303446"
#
#[colors.dim]
#black = "#51576D"
#blue = "#8CAAEE"
#cyan = "#81C8BE"
#green = "#A6D189"
#magenta = "#F4B8E4"
#red = "#E78284"
#white = "#B5BFE2"
#yellow = "#E5C890"
#
#[colors.hints.end]
#background = "#A5ADCE"
#foreground = "#303446"
#
#[colors.hints.start]
#background = "#E5C890"
#foreground = "#303446"
#
#[colors.normal]
#black = "#51576D"
#blue = "#8CAAEE"
#cyan = "#81C8BE"
#green = "#A6D189"
#magenta = "#F4B8E4"
#red = "#E78284"
#white = "#B5BFE2"
#yellow = "#E5C890"
#
#[colors.primary]
#background = "#303446"
#bright_foreground = "#C6D0F5"
#dim_foreground = "#C6D0F5"
#foreground = "#C6D0F5"
#
#[colors.search.focused_match]
#background = "#A6D189"
#foreground = "#303446"
#
#[colors.footer_bar]
#background = "#A5ADCE"
#foreground = "#303446"
#
#[colors.search.matches]
#background = "#A5ADCE"
#foreground = "#303446"
#
#[colors.selection]
#background = "#F2D5CF"
#text = "#303446"
#
#[colors.vi_mode_cursor]
#cursor = "#BABBF1"
#text = "#303446"
#
[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13
offset.y = 1

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"


[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 1
y = 1
